---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'cloud/**'
      - 'doc/**'
      - 'fuzzer/**'
      - 'ide/**'
      - 'kobo/**'
      - 'python/**'
      - '.github/workflow/**'
    branches:
      - main


env:
  DEBUG: y

jobs:
  
  build-android:
    runs-on: ubuntu-22.04

    env:
      TARGET: ANDROIDFAT
      TARGET_BIN: XCSoar-debug
      TARGET_FINAL: XCSoar-debug
      TARGET_EXT: apk

    steps:
      - name: set vars for push
        if: github.event_name == 'push'
        run: |
          echo "DEBUG=n" >> $GITHUB_ENV
          echo "TARGET_FINAL=XCSoar" >> $GITHUB_ENV
      - id: checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ matrix.os }}-${{ matrix.type }}-${{ env.TARGET }}

      - name: "Cache third-party libraries"
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-libs-${{ env.TARGET }}-${{ hashFiles('build/**') }}
          path: |
            ${{ github.workspace }}/output/ANDROID/*/lib
            !${{ github.workspace }}/output/ANDROID/*/lib/build
      - name: find githash
        run: |
          echo "git_hash=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            make \
            quilt \
            g++ \
            librsvg2-bin xsltproc \
            imagemagick gettext sox \
            vorbis-tools \
            cmake ninja-build
      - name: Compile XCSoar
        run: |
          make -j$(nproc) \
            TARGET=${{env.TARGET}} \
            ANDROID_NDK=${ANDROID_NDK_LATEST_HOME} \
            ANDROID_SDK=${ANDROID_HOME} \
            DEBUG=${{env.DEBUG}} \
            USE_CCACHE=y \
            V=2
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.TARGET_FINAL }}-${{ env.git_hash }}.${{ env.TARGET_EXT }}
          path: output/ANDROID/bin/${{ env.TARGET_BIN }}.${{ env.TARGET_EXT }}
