---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'cloud/**'
      - 'doc/**'
      - 'fuzzer/**'
      - 'ide/**'
      - 'kobo/**'
      - 'python/**'
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 5f6d5ce... PEV function update
      - '.github/workflows/**'
      - 'README.md'
<<<<<<< HEAD
    branches:
      - main
=======
<<<<<<< HEAD
=======
      - '.github/workflows/build-container.yml'
      - '.github/workflows/build-unix.yml'
=======
      - '.github/workflows/**'
<<<<<<< HEAD
      - 'Readme.md'
>>>>>>> Update android.yml
=======
      - 'README.md'
>>>>>>> dd2c954... Update android.yml
=======
      - '.github/workflows/**'
      - 'Readme.md'
>>>>>>> 81a87eb... Update android.yml
    branches:
      - master
>>>>>>> Create android.yml
=======
>>>>>>> 5f6d5ce... PEV function update
      - '.github/workflows/build-container.yml'
      - '.github/workflows/build-unix.yml'
=======
      - '.github/workflows/**'
<<<<<<< HEAD
      - 'Readme.md'
<<<<<<< HEAD
>>>>>>> Update android.yml
=======
      - 'README.md'
>>>>>>> abee37c... Update android.yml
=======
>>>>>>> dd2c954... Update android.yml
    branches:
      - master
>>>>>>> Create android.yml
=======
>>>>>>> 81a87eb... Update android.yml
=======
      - '.github/workflows/**'
      - 'Readme.md'
>>>>>>> 1f78c76... Update android.yml
    branches:
<<<<<<< HEAD
<<<<<<< HEAD
      - master
>>>>>>> 8807698... Create android.yml
=======
      - main
>>>>>>> d9d3bfd... Update android.yml
>>>>>>> 5f6d5ce... PEV function update
=======
      - '.github/workflows/build-container.yml'
      - '.github/workflows/build-unix.yml'
    branches:
      - master
>>>>>>> 8807698... Create android.yml
=======
      - main
>>>>>>> d9d3bfd... Update android.yml

  pull_request:
    paths-ignore:
      - 'cloud/**'
      - 'doc/**'
      - 'fuzzer/**'
      - 'ide/**'
      - 'kobo/**'
      - 'python/**'
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 5f6d5ce... PEV function update
      - '.github/workflows/**'
      - 'README.md'
    branches:
      - main
=======
      - '.github/workflows/build-container.yml'
      - '.github/workflows/build-unix.yml'
=======
      - '.github/workflows/**'
<<<<<<< HEAD
      - 'Readme.md'
>>>>>>> Update android.yml
<<<<<<< HEAD
=======
      - '.github/workflows/**'
      - 'Readme.md'
>>>>>>> 1f78c76... Update android.yml
    branches:
<<<<<<< HEAD
      - master
>>>>>>> Create android.yml
=======
=======
      - '.github/workflows/**'
<<<<<<< HEAD
<<<<<<< HEAD
      - 'Readme.md'
>>>>>>> 81a87eb... Update android.yml
=======
      - 'README.md'
>>>>>>> abee37c... Update android.yml
=======
      - '.github/workflows/**'
      - 'Readme.md'
>>>>>>> 81a87eb... Update android.yml
    branches:
<<<<<<< HEAD
      - master
>>>>>>> Create android.yml
=======
      - '.github/workflows/build-container.yml'
      - '.github/workflows/build-unix.yml'
=======
      - 'README.md'
>>>>>>> dd2c954... Update android.yml
=======
      - 'README.md'
>>>>>>> dd2c954... Update android.yml
    branches:
<<<<<<< HEAD
      - master
>>>>>>> 8807698... Create android.yml
=======
      - main
>>>>>>> 4703a0e... Update android.yml
>>>>>>> 5f6d5ce... PEV function update
=======
      - main
>>>>>>> e15bd95... Update android.yml
=======
      - '.github/workflows/build-container.yml'
      - '.github/workflows/build-unix.yml'
    branches:
      - master
>>>>>>> 8807698... Create android.yml
=======
      - main
>>>>>>> 4703a0e... Update android.yml

env:
  DEBUG: y

jobs:
  
  build-android:
    runs-on: ubuntu-22.04

    env:
      TARGET: ANDROIDFAT
      TARGET_BIN: XCSoar-debug
      TARGET_FINAL: XCSoar-debug
      TARGET_EXT: apk

    steps:
      - name: set vars for push
        if: github.event_name == 'push'
        run: |
          echo "DEBUG=n" >> $GITHUB_ENV
          echo "TARGET_FINAL=XCSoar" >> $GITHUB_ENV
      - id: checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ matrix.os }}-${{ matrix.type }}-${{ env.TARGET }}

      - name: "Cache third-party libraries"
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-libs-${{ env.TARGET }}-${{ hashFiles('build/**') }}
          path: |
            ${{ github.workspace }}/output/ANDROID/*/lib
            !${{ github.workspace }}/output/ANDROID/*/lib/build
      - name: find githash
        run: |
          echo "git_hash=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            make \
            quilt \
            g++ \
            librsvg2-bin xsltproc \
            imagemagick gettext sox \
            vorbis-tools \
            cmake ninja-build
      - name: Compile XCSoar
        run: |
          make -j$(nproc) \
            TARGET=${{env.TARGET}} \
            ANDROID_NDK=${ANDROID_NDK_LATEST_HOME} \
            ANDROID_SDK=${ANDROID_HOME} \
            DEBUG=${{env.DEBUG}} \
            USE_CCACHE=y \
            V=2
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.TARGET_FINAL }}-${{ env.git_hash }}.${{ env.TARGET_EXT }}
          path: output/ANDROID/bin/${{ env.TARGET_BIN }}.${{ env.TARGET_EXT }}

      - name: Deploy to Staging server
        if: |
          github.repository == 'XCSoar/XCSoar' &&
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
          github.ref == 'ref/head/main' &&
=======
          github.ref == 'ref/head/master' &&
>>>>>>> Create android.yml
=======
<<<<<<< HEAD
<<<<<<< HEAD
          github.ref == 'ref/head/main' &&
=======
          github.ref == 'ref/head/master' &&
>>>>>>> Create android.yml
=======
          github.ref == 'ref/head/master' &&
>>>>>>> 8807698... Create android.yml
=======
          github.ref == 'ref/head/main' &&
>>>>>>> de62913... Update android.yml
>>>>>>> 5f6d5ce... PEV function update
=======
          github.ref == 'ref/head/main' &&
>>>>>>> 85a22ed... Update android.yml
=======
          github.ref == 'ref/head/master' &&
>>>>>>> 8807698... Create android.yml
=======
          github.ref == 'ref/head/main' &&
>>>>>>> de62913... Update android.yml
          github.event == 'push'
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.REPOSITORY_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: output/${{ env.TARGET }}/bin/${{ env.TARGET_BIN }}.${{ env.TARGET_EXT }}
          REMOTE_HOST: ${{ secrets.REPOSITORY_HOST }}
          REMOTE_USER: ${{ secrets.REPOSITORY_SSH_USER }}
          TARGET: ${{ secrets.REPOSITORY_REMOTE_PATH }}/testing/${{ env.TARGET }}/
